import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {CSPostHogProvider} from "@/app/providers";
import {getBootstrapData} from "@/app/utils/getBootstrapData";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const bootstrapData = await getBootstrapData()
  return (
    <html lang="en">
    <CSPostHogProvider bootstrapData={bootstrapData}>
      <body>{children}</body>
    </CSPostHogProvider>
    </html>
  );
}
